ARDUINO_DIR = /home/nicoleg/arduino-1.8.15
ARDUINO_PORT = /dev/ttyAMC*

USER_LIB_PATH = /home/nicoleg/swarm_ws/arduino_code/lib_test/ros_lib
BOARD_TAG = teensy36

include /usr/share/arduino/Teensy.mk
