# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msgs/Speed_tick.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Speed_tick(genpy.Message):
  _md5sum = "49db339e4cdd08bb4996af3a92cbcc3d"
  _type = "custom_msgs/Speed_tick"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# This represents the right and left speed plus the right and left tick

float64 right_speed
float64 left_speed
int32 right_tick
int32 left_tick
"""
  __slots__ = ['right_speed','left_speed','right_tick','left_tick']
  _slot_types = ['float64','float64','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       right_speed,left_speed,right_tick,left_tick

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Speed_tick, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.right_speed is None:
        self.right_speed = 0.
      if self.left_speed is None:
        self.left_speed = 0.
      if self.right_tick is None:
        self.right_tick = 0
      if self.left_tick is None:
        self.left_tick = 0
    else:
      self.right_speed = 0.
      self.left_speed = 0.
      self.right_tick = 0
      self.left_tick = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2d2i().pack(_x.right_speed, _x.left_speed, _x.right_tick, _x.left_tick))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.right_speed, _x.left_speed, _x.right_tick, _x.left_tick,) = _get_struct_2d2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2d2i().pack(_x.right_speed, _x.left_speed, _x.right_tick, _x.left_tick))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.right_speed, _x.left_speed, _x.right_tick, _x.left_tick,) = _get_struct_2d2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d2i = None
def _get_struct_2d2i():
    global _struct_2d2i
    if _struct_2d2i is None:
        _struct_2d2i = struct.Struct("<2d2i")
    return _struct_2d2i
